name: CI–FastAPI

on:
  pull_request:
    branches: [main]
  push:
    branches: [dev]

permissions:
  contents: read

jobs:
  # Job 1 : Analyse de sécurité des dépendances
  security-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies and Safety
        run: |
          python -m pip install --upgrade pip
          pip install --force-reinstall --no-cache-dir -r requirements-dev.txt
          # Mettre à jour setuptools, wheel et passer à Safety 3+
          pip install --upgrade "setuptools>=83.0.0" "wheel>0.46.1" safety

      - name: Check for security issues
        env:
          PYTHONWARNINGS: "ignore::DeprecationWarning"
        run: |
          safety check

  # Job 2 : Tests (s'exécutent uniquement si security-check réussit)
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (dev)
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade "setuptools>=83.0.0" "wheel>0.46.1"
          pip install -r requirements-dev.txt
          pip list

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov-report=xml --cov-report=term-missing